### ISSUE TITLE
Defining category twice

### ISSUE THREAD

**Issue by MRKnutson** [XavioArts/psa10_app#101]
# Issue
Category is defined at both the collection and the card level

# Steps to reproduce
Create collection and then create card

# Expected result
category defined at collection level (at minimum autofill collection appropriately at card level)

# Actual Result
Asks for category to be defined twice

![Screen Shot 2022-01-28 at 9 14 34 AM](https://user-images.githubusercontent.com/80441300/151605923-80465e0d-7425-4efb-af42-7fb99ba00b7c.png)

**Comment by madelines-code** [comment]
Asking Will about this.
