### ISSUE TITLE
Might want to limit how long a user name can be

### ISSUE THREAD

**Issue by DennyPlank** [XavioArts/psa10_app#103]
Long User info can be hard on the sylin
![76B6D098-528E-4C0C-972D-536C5FACC080_4_5005_c](https://user-images.githubusercontent.com/67938665/151606338-0261491a-134a-4d6c-b667-eeeff16c62d2.jpeg)
g

**Comment by DennyPlank** [comment]
Issue: when creating or updating a profile, the current llimits allow for too long of name or usernames

**Comment by DennyPlank** [comment]
![FFC1895D-9389-45F7-AAC9-3C860CBCF1C0_1_105_c](https://user-images.githubusercontent.com/67938665/151607457-cf5362e3-f7e5-431d-97b0-67487a95d21d.jpeg)

**Comment by jleosco** [comment]
bug fixed
