### ISSUE TITLE
Random number 5 on showcases page

### ISSUE THREAD

**Issue by MRKnutson** [XavioArts/psa10_app#112]
# Suggestion

# Issue
There is a random 5 on far left of empty showcases page

# Steps to reproduce
go to showcases page before making any showcases

# Expected result
no number 5

# Actual Result
number 5

![Screen Shot 2022-01-28 at 9 37 45 AM](https://user-images.githubusercontent.com/80441300/151607560-e1049264-249f-4be6-ae6a-20fa1803a8a6.png)

**Comment by jleosco** [comment]
Bug fixed
