### ISSUE TITLE
Constant warning to finish profile

### ISSUE THREAD

**Issue by MRKnutson** [XavioArts/psa10_app#114]
# Suggestion

# Issue
It's really annoying to have constant warning to build out profile. I usually don't want to give all possible info

# Steps to reproduce
don't fill out entire profile

# Expected result
Some way to silence notification or just no notification at all

# Actual Result
constant warning entire time I'm using app

**Comment by madelines-code** [comment]
This should only be true for first name, last namem username and profile image. The rest should be optional. Did you find otherwise?

**Comment by MRKnutson** [comment]
@madelines-code Just saw your question. I don't remember what I put in but I have a tendency to just put in the minimum I have to. Perhaps at least put asterix next to required fields. I very likely only would put in a first name and email otherwise. If you are going to make certain things required I would also suggest that you have the information all collected on registration page.
