### ISSUE TITLE
Making blank posts in the discussion forum

### ISSUE THREAD

**Issue by DennyPlank** [XavioArts/psa10_app#94]
Issue: You can make blank topics in the forum. There should be a validation to prevent this

![A9E28643-8803-4297-897C-3DAC1C36A3FF_1_105_c](https://user-images.githubusercontent.com/67938665/151604283-429d82f3-64f7-460d-bb78-44f7f46ab5f9.jpeg)
.

**Comment by jleosco** [comment]
bug fixed
