### ISSUE TITLE
Really long showcase names can throw off the app styling

### ISSUE THREAD

**Issue by DennyPlank** [XavioArts/psa10_app#98]
If you make a showcase with a long name, Theres no limit to how long that name can be displayed
![Screen Shot 2022-01-28 at 10 52 34 AM](https://user-images.githubusercontent.com/67938665/151604909-357c4b5f-3433-4da3-b461-ef20af715de9.png)
.

**Comment by Vitamin-Ccc** [comment]
limited maxlength to 40 characters
